### ISSUE TITLE
Hi! When will the code be released?

### ISSUE THREAD

**Issue by DLwbm123** [imirzadeh/MC-SGD#1]

**Comment by imirzadeh** [comment]
Hi,

Please see here: [https://github.com/imirzadeh/CL-Gym/blob/main/cl_gym/algorithms/mcsgd.py](https://github.com/imirzadeh/CL-Gym/blob/main/cl_gym/algorithms/mcsgd.py) or [here](https://github.com/imirzadeh/CL-LinearModeConnectivity/blob/master/core/train_methods.py#L82). 

In addition, you can see appendix of the paper and see full code/experiment details for rotated MNIST benchmark.
